version: 2.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello World"

